server:
  port: 8060

zuul:
  routes:
    api-service:
      path: /webapi/v1/**
      url: http://localhost:9898/
      stripPrefix: false

management.security.enabled: false

---
spring:
  profiles: local