server:
  port: 8060
  session:
    cookie:
      max-age: 604800

zuul:
  routes:
    api-service:
      path: /webapi/v1/**
      url: http://localhost:9898/
      stripPrefix: false

management.security.enabled: false

spring:
  session:
    store-type: redis

---
spring:
  profiles: local
  redis:
    host: localhost
    port: 6379